/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBadge: typeof import('element-plus/lib')['ElBadge']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElInputNumber: typeof import('element-plus/lib')['ElInputNumber']
    ElRow: typeof import('element-plus/lib')['ElRow']
  }
}
